- html lang="en":
    - head:
        - $partial: seo1
          page: ${page}
          seo: ${seo}
        - link rel="stylesheet" href="/public/theme.css":
        - script src="https://cdn.jsdelivr.net/npm/@rettangoli/ui@1.0.0-rc12/dist/rettangoli-iife-ui.min.js":
        - script src="/public/rtgl-icons.js":

    - body.dark:
        - rtgl-view w=f:
            - rtgl-view h="48":
            - rtgl-view w="f" ah="c":
                - rtgl-view w=f ph="lg" pb="lg" ah=c:
                    - "${content}"
                - rtgl-view d="h" h="30vh":
                - $partial: footer1
            - rtgl-view pos="abs" edge="t" ah="c" bgc="bg":
                - $partial: navbar1
                  title: ${site.navbar.title}
                  cta: ${site.navbar.cta}
